version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: .
    command: ["./demo-backend"]
    ports:
      - "8081:8081"

  middleware:
    build: .
    command: ["./rate-limiter-server"]
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8081
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
      - backend
